name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60 

    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.x]

    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Run tests and capture report
        run: npm test -- --reporter=json
        env:
          CI: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
